# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import ngs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('forward', models.FileField(upload_to=ngs.models.user_directory_path)),
                ('reverse', models.FileField(upload_to=ngs.models.user_directory_path)),
            ],
        ),
    ]
