# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-10 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import ngs.models


class Migration(migrations.Migration):

    dependencies = [
        ('ngs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequencingFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('SeqFiles', models.FileField(upload_to=ngs.models.user_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
